---
driver: 
  name: docker

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[gh_test]
  attributes: 
    gh_test:
      test_repo: <%= ENV['test_repo'] %>/web
      oauth_token: <%= ENV['github_token'] %>
      hook_config: 
        url: http://google.com
